CAMINHO_PASTA_ARQUIVOS = "archives/"

CAMINHO_ARQUIVO_CLIENTES_CTA = "archives/Clientes.csv"
CAMINHO_ARQUIVO_CLIENTES_FORMATADOS = "archives/Clientes Formatados.csv"

CAMINHO_ARQUIVO_PRODUTOS_CTA = "archives/PRODUTOS.CSV"
CAMINHO_ARQUIVO_PRODUTOS_FORMATADOS = "archives/Produtos Formatados.csv"
