COR_FUNDO = ("#0F172A", "#F8FAFC")
COR_TEXTO = ("#111827", "#FFFFFF")
COR_ACCENT = ("#2563EB", "#2563EB")

COR_LINHAS = ("#1F2937", "#E5E7EB")

COR_BOTAO = ("#979DA2", "#4A4D50")
HOVER_BOTAO = ("#D5D5D5", "#3A3A3A")
COR_TEXTO_BOTAO = ("#FFFFFF", "#FFFFFF")

COR_BACKGROUND_HEADING_TREE = "#343638"
COR_FOREGROUND_HEADING_TREE = "#FFFFFF"

COR_BACKGROUND_HEADING_HOVER_TREE = "#4A4D50"
COR_FOREGROUND_HEADING_HOVER_TREE = "#FFFFFF"

COR_BACKGROUND_VALORES_HOVER_TREE = "#bfc5c2"
COR_FOREGROUND_VALORES_HOVER_TREE = "#FFFFFF"