BACKGROUND = "#0F172A"
FOREGROUND = "#FFFFFF"

HEADERSBACKGROUND = "#1F2937"
HEADERSFOREGROUND = "#FFFFFF"

NORMALBACKGROUND = "#0F172A"
NORMALFOREGROUND = "#E5E7EB"

WEEKENDBACKGROUND = "#0F172A"
WEEKENDFOREGROUND = "#D1D5DB"

SELECTBACKGROUND = "#4A4D50"
SELECTFOREGROUND = "#FFFFFF"

BORDERCOLOR = "#1F2937"
BORDERWIDTH = 1
